[tool.poetry]
name = "mt-dashboard-backend"
version = "0.1.0"
description = ""
authors = ["Masaya <masaya.ajiro@renue.co.jp>"]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11,<3.13"
fastapi = "^0.115.5"
uvicorn = {extras = ["standard"], version = "^0.32.1"}
google-api-python-client = "^2.153.0"
google-auth = "^2.36.0"
pandas = "^2.2.3"
openai = "^1.54.4"
python-dotenv = "^1.0.1"
google-cloud-secret-manager = "^2.21.1"
google-cloud-bigquery = "^3.27.0"
pandas-gbq = "^0.24.0"
httpx = "^0.28.1"
google-auth-oauthlib = "^1.2.1"
google-auth-httplib2 = "^0.2.0"
bcrypt = "^4.2.0"
slowapi = "^0.1.9"

[tool.poetry.group.dev.dependencies]
pytest = "^8.3.0"
pytest-asyncio = "^0.24.0"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
